Fix floating point rounding error
Harekaze/Harekaze-iOS pull request #6
Opened 2016-10-08 09:01 UTC by yaslab

Recordings 画面の時刻表示が1分ずれていることがあったので、調べていたら原因がわかったので PR します。

### Description

JSON からモデルクラス `Program` にマッピングする際、`TimeDateTransform` クラスを使って Unix Time (ms 単位) を `Date` に変換していますが、Unix Time を `Float` 型で扱っているために誤差が発生しています。
（ms 単位の Unix Time を扱うには `Float` 型では桁数が足りません・・・）

### Technical Changes 
 
- `Float` 型を `Double` 型に変更

### Related issues

- 特になし

2016-10-09 02:52 UTC, yaslab commented
CI でビルドエラーが出てますね。

```
❌  /Users/travis/build/Harekaze/Harekaze-iOS/Harekaze/Transitions/ShowDetailTransition.swift:61:7: type 'ShowDetailTransition' does not conform to protocol 'TransitionAnimatable'
class ShowDetailTransition: TransitionAnimatable {
      ^
```

`TransitionAnimatable` を `ShowDetailTransition` の extension で実装しているのが原因な気がするので修正してみます。

2016-10-09 03:05 UTC, yaslab commented
原因違いましたね。
ARNTransitionAnimator がアップデートしているようです。

2016-10-09 09:51 UTC, mzyy94 commented
全然気づいていませんでした。
ARNTransitionAnimator部分の修正と同時にマージします。
調査から修正までありがとうございます。

2016-10-10 08:57 UTC, yaslab commented
ARNTransitionAnimator は Podfile でタグ 2.0.0 を指定して使用していますが、タグ 2.0.0 が指すコミットが変わったっぽいです。
どんな修正が入ったかまでは追っていませんが、とりあえずビルドが通るようにしました。

2016-10-10 12:43 UTC, mzyy94 commented
ありがとうございます。
こちらでもビルド通過を確認しました。
まもなくマージいたします。

2016-10-12 06:12 UTC, mzyy94 requested changes
Please check some comments

2016-10-12 06:12 UTC, mzyy94 commented on Harekaze/Transitions/ShowDetailTransition.swift
> +    func prepareContainer(_ transitionType: TransitionType, containerView: UIView, from fromVC: UIViewController, to toVC: UIViewController) {
Please use Hard Tab instead of 4 spaces.

2016-10-12 06:12 UTC, mzyy94 commented on Harekaze/Transitions/ShowDetailTransition.swift
> +    func prepareContainer(_ transitionType: TransitionType, containerView: UIView, from fromVC: UIViewController, to toVC: UIViewController) {
Below one, too

2016-10-13 11:19 UTC, yaslab commented on Harekaze/Transitions/ShowDetailTransition.swift
> +    func prepareContainer(_ transitionType: TransitionType, containerView: UIView, from fromVC: UIViewController, to toVC: UIViewController) {
すみません、空白文字は意識していませんでした。
修正いたします。

2016-10-13 11:49 UTC, yaslab commented
スペース4つをタブに修正しました。

この PR で議論する内容ではないかもしれませんが、インデントの際に Hard Tab が挿入されるようにプロジェクトレベルで設定しておいてはいかがでしょうか？

<img width="959" alt="text-settings" src="https://cloud.githubusercontent.com/assets/2077275/19347934/62445518-9186-11e6-93e0-6684fe0f75cc.png">

2016-10-13 11:55 UTC, yaslab commented
しっかりチェックできていなくてすみません・・・
空行に Space が残っていたので削除しました。

2016-10-13 12:38 UTC, mzyy94 commented
レビュー内容の修正ありがとうございます。
たしかにおっしゃる通りプロジェクトレベルでのハードタブ利用に設定しておきます。
（設定したつもりでいました；；）

2016-10-13 12:38 UTC, merged